config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :detect_device_variant
  
  private
    
  def detect_device_variant
    request.variant = :phone if browser.device.mobile?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    def home
    end
    
    def about
    end
    
    def contact
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns title of page
    def full_title(page_title = '')
        base_title = "Test Website"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_application_layout.html.erb
<body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% #debug(params) if Rails.env.development? %>
    </div>
</body>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-static-bottom">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="container" id="logo">test</div>
        <div class="container" id="logo-two">test</div>
    </div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path, id: "logo-three" %></li>
                <li><%= link_to "About", about_path, id: "logo-three" %></li>
                <li><%= link_to "Contact", contact_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_phone_header.html.erb
<span class="mobile-menu" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>


<div id="myNav" class="overlay">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <div class="overlay-content">
        
        <div class="container" id="logo">Test</div>
        <div class="container" id="logo-two">test</div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path, id: "logo-three" %></li>
                <li><%= link_to "About", about_path, id: "logo-three" %></li>
                <li><%= link_to "Contact", contact_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </div>
  </div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:url"           content="url goes here" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Website" />
  <meta property="og:description"   content="Website" />
  <meta property="og:image"         content="assets/#" />
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= favicon_link_tag '#' %>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/phone_header' %>
  </head>
    <body>
    <%= render 'layouts/application_layout' %>
</body>
</html>
<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Pinyon+Script" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Italianno|Mr+De+Haviland" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Miss+Fajardose|Monsieur+La+Doulaise|Rouge+Script" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:url"           content="url goes here" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Website" />
  <meta property="og:description"   content="Website" />
  <meta property="og:image"         content="assets/#" />
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= favicon_link_tag '#' %>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/header' %>
  </head>
    <body>
    <%= render 'layouts/application_layout' %>
</body>
</html>
<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Pinyon+Script" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Italianno|Mr+De+Haviland" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Miss+Fajardose|Monsieur+La+Doulaise|Rouge+Script" rel="stylesheet">

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html+phone.erb
<% provide(:title, "About") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
   
</meta>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

app/views/static_pages/contact.html+phone.erb
<% provide(:title, "Contact") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
   
</meta>    

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

app/views/static_pages/home.html+phone.erb
<% provide(:title, "Home") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <body id="homephone">
       
    </body>
</meta>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div id="home"></div>

<p id="timer"></p>